<?php

namespace HegesApp\ConfigFileBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DataRepository extends EntityRepository
{
	
	
	public function findByfkConfiglineorderbyfield($id)
	{
		
		
		return $this->getEntityManager()
		->createQuery('select a from HegesAppConfigFileBundle:Data a,
				HegesAppConfigFileBundle:Configfield b
				where a.fkConfigline= :id
				and a.fkConfigfield=b.id
				order by b.fieldorder')
		->setParameter('id', $id)
		->getResult();
	}
	
	
}
