parameters:
#    heges_app_monitor.example.class: HegesApp\MonitorBundle\Example

services:
#    heges_app_monitor.example:
#        class: %heges_app_monitor.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
