parameters:
#    heges_app_service.example.class: HegesApp\ServiceBundle\Example

services:
#    heges_app_service.example:
#        class: %heges_app_service.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
