parameters:
#    heges_app_config_file.example.class: HegesApp\ConfigFileBundle\Example

services:
#    heges_app_config_file.example:
#        class: %heges_app_config_file.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
