parameters:
#    heges_app_main.example.class: HegesApp\MainBundle\Example

services:
#    heges_app_main.example:
#        class: %heges_app_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
