<?php

namespace HegesApp\NodeBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
	
	
	public function getAllNodes()
	{
		return $this->getEntityManager()
		->createQuery('select p from HegesAppNodeBundle:Node p order by p.name ASC')
		->getResult();
	
	}
	
	public function getOvonodestatus($nodename)
	{
		$dbh=new \PDO('oci:dbname=172.31.207.100/ovp1','opc_report','opc_report');
	
		$select="select C.NODE_GROUP_NAME as ESTADO
		from OPC_NODES A, OPC_NODES_IN_GROUP B, OPC_NODE_GROUPS C
		where A.LABEL='".$nodename."'
		and A.NODE_ID=B.NODE_ID
		and B.NODE_GROUP_ID=C.NODE_GROUP_ID";
	
	
		$query = $dbh->prepare($select);
		$query->execute();
		$nodestatus=array();
		while ($data = $query->fetch(\PDO::FETCH_ASSOC)) {

			$data['ESTADO']=str_replace('NAG_','',$data['ESTADO']);
			
			switch($data['ESTADO']){
				
				case "PRODUCCION":
					$data['ESTADO']="PRODUCCION";
					break;
				case "PREPRODUCCION":
					$data['ESTADO']="PREPRODUCCION";
					break;										
				case "DESARROLLO":
					$data['ESTADO']="DESARROLLO";
					break;
				case "INSTALACION":
					$data['ESTADO']="INSTALACION";
					break;										
				case "BAJAS":
					$data['ESTADO']="INSTALACION";
					break;

			}
			array_push($nodestatus,$data['ESTADO']);
			
		}
		
		if (in_array("PRODUCCION",$nodestatus)){return "PRODUCCION";}
		if (in_array("PREPRODUCCION",$nodestatus)){return "PREPRODUCCION";}
		if (in_array("DESARROLLO",$nodestatus)){return "DESARROLLO";}
		if (in_array("INSTALACION",$nodestatus)){return "INSTALACION";}
		if (in_array("BAJAS",$nodestatus)){return "BAJA";}		
		return "NO_MONITORIZADO";
	
	}
	
	
}


