parameters:
#    heges_app_performance.example.class: HegesApp\PerformanceBundle\Example

services:
#    heges_app_performance.example:
#        class: %heges_app_performance.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
